# Generated by Django 4.2.7 on 2023-12-29 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_userbackaccount_userbankaccount'),
        ('transactions', '0003_alter_transfermoney_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfermoney',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='money_received', to='accounts.userbankaccount'),
        ),
    ]
